plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.seleniumhq.selenium:selenium-java:4.24.0'
    testImplementation 'io.github.bonigarcia:webdrivermanager:5.9.2'
    testImplementation 'io.cucumber:cucumber-java:7.18.1'
    testImplementation 'io.cucumber:cucumber-junit:7.18.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.11.0'
    testImplementation 'org.junit.vintage:junit-vintage-engine:5.11.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.0'
    
    testImplementation 'io.qameta.allure:allure-maven:2.14.0' {
        exclude group: 'com.google.guava', module: 'guava'
        exclude group: 'com.google.collections', module: 'google-collections'
    }
    
    testImplementation 'io.rest-assured:rest-assured:5.5.0'
    testImplementation 'org.json:json:20240303'
    testImplementation 'io.rest-assured:json-schema-validator:5.5.0'
}


configurations.all {
    resolutionStrategy {
        force 'com.google.guava:guava:33.2.1-jre'
        force 'com.google.collections:google-collections:1.0'
    }
}

test {
    useJUnitPlatform()
}
